name: flash_hansika
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #  sqflite: ^2.2.4+1
  #  path:^1.8.0

  cupertino_icons: ^1.0.2     #to use icons
  geolocator: ^9.0.2          #to use location
  http: ^0.13.5               #helps in using http resources
  flutter_spinkit: ^5.1.0     #for using loading spinner
  animated_text_kit: ^4.2.2   #to give animation
  firebase_core: ^2.4.1       #for firebase initialization
  firebase_auth: ^4.2.5       #firebase autherization
  cloud_firestore: ^4.3.1     #firestore
  modal_progress_hud: ^0.1.3  #widget wrapper to display heads up display


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Unbounded
      fonts:
        - asset: fonts/Unbounded-VariableFont_wght.ttf